# Teaching Experience

I taught 100+ hours on Ecology, Biodiversity Statistics, and R programming from 2nd year of Bachelor to PhD students (detail below).

I am a certified [Carpentries](https://carpentries.org/) instructor, focusing on **R programming** and **Data Visualization**.

I also founded the R User Group at the Center for Functional and Evolutionary Ecology in Montpellier. There, I organized regular 1h meet-ups on various R topics (plotting with `ggplot2`, mapping with `sf`, project organization with RStudio, workflow organization with `drake`, parallelization with `future`).

**Teaching detail**

| Course Name                  | Year(s) | Level          | Total time |
|------------------------------|---------|----------------|------------|
| Descriptive Statistics with R (UM)    | 2016/2017 | Bachelor’s (2nd yr) | 50h |
| Functional Biogeography with R (UM, [material](https://github.com/Rekyt/functional_biogeo_practical)) | 2017/2018 | Master’s (2nd yr) | 8h |
| Guest Lecture on Biodiversity Facets (UL) | 2021/2022 | Master's (1st yr) | 4h |
| Biodiversity Facets with R (UL, [material](https://rekyt.github.io/biodiversity_facets_tutorial/)) | 2021/2022 | Master's (1st yr) | 12h |
| Group project on Biodiversity Facets (UL) | 2021 | Master's (1st yr) | 20h |
| Introduction to git and GitHub (UL/iDiv, [material](https://emilio-berti.github.io/idiv-git-introduction)) | 2022 | Masters, PhD students, and postdocs | 10h |

UM: University of Montpellier; UL: University of Leipzig
