---
name: Matthias
surname: Grenié
position: "Chercheur Postdoctoral"
address: "German Centre for Integrative Biodversity Research (iDiv), Halle-Jena-Leipzig"
phone: +49 341 9733176
csl: "csl/apa-6.csl"
orcid: 0000-0002-4659-7522
www: rekyt.github.io
email: "matthias.grenie@idiv.de"
twitter: LeNematode
github: Rekyt
scholar: "fZ1_d7QAAAAJ"
researchgate: Matthias-Grenie
date: "`r withr::with_locale(c(LC_TIME = 'fr_FR'), {format(Sys.time(), '%B %Y')})`"
output:
  vitae::hyndman:
    keep_tex: true
    keep_md: true
    pandoc_args:
      - --lua-filter="lua/strong.lua"
header-includes:
  - \definecolor{headcolor}{HTML}{1E49BF}
  - \definecolor{linkscolor}{HTML}{026dbb}
  - \hypersetup{colorlinks=true, linkcolor=linkscolor, filecolor=linkscolor, urlcolor=linkscolor, urlbordercolor=linkscolor}
---

```{r setup, include=FALSE}
Sys.setlocale(locale = "fr_FR")

knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library("vitae")
library("dplyr")
```


```{r child-education, child="parts/fr/01-education.Rmd"}
```

```{r child-experience, child="parts/fr/02-academic-experience.Rmd"}
```

\newpage

```{r child-supervision, child="parts/fr/03-supervision.Rmd"}
```

```{r child-service, child="parts/fr/04-service.Rmd"}
```

```{r child-projects, child="parts/fr/05-projects.Rmd"}
```


```{r child-funding, child="parts/fr/06-funding.Rmd"}
```

```{r child-contributions, child="parts/fr/07-00-contributions.Rmd"}
```

\newpage

```{r child-teaching, child="parts/fr/08-teaching.Rmd"}
```

```{r child-skills, child="parts/fr/09-skills.Rmd"}
```

