## R packages

* **`funrar`** (creator and maintainer)
\hfill\break Compute functional rarity indices, major tool for the work of the FREE CESAB group
\hfill\break &nbsp;[\faFile*&nbsp; published paper](https://doi.org/10.1111/ddi.12629) -- [\faRProject&nbsp;CRAN](https://cran.r-project.org/package=funrar) -- [\faGithub&nbsp;GitHub](https://github.com/Rekyt/funrar)

* **`ecolottery`** (co-creatore)
\hfill\break efficient simulation of community assembly processes, including both neutral and niche processes
\hfill\break &nbsp;[\faFile*&nbsp; published paper](https://doi.org/10.1111/2041-210X.12918) -- [\faRProject&nbsp;CRAN](https://cran.r-project.org/package=ecolottery) -- [\faGithub&nbsp;GitHub](https://github.com/frmunoz/ecolottery)

* **`fundiversity`** (co-creator and maintainer)
\hfill\break compute functional diversity indices in an efficient way, modular, with modern computation features out-of-the-box (parallelization, memoization)
\hfill\break &nbsp;[\faFile*&nbsp; published paper](https://doi.org/10.1111/ecog.06585) -- [\faRProject&nbsp;CRAN](https://cran.r-project.org/package=fundiversity) -- [\faGithub&nbsp;GitHub](https://github.com/bisaloo/fundiversity)

* **`funbiogeo`** (co-creator and maintainer)
\hfill\break ease functional biogeography analyses, developed within FREE CESAB group
\hfill\break &nbsp;[\faGithub&nbsp;GitHub](https://github.com/FRBCesab/funbiogeo)

* **`rtaxref`** (creator and maintainer)
\hfill\break access the data of the French Taxonomic Reference (TAXREF) API
\hfill\break &nbsp;[\faGithub&nbsp;GitHub](https://github.com/Rekyt/rtaxref)

* Significant contributions to other R packages: [**`taxize`**](https://cran.r-project.org/package=taxize) (extract and standardize taxonomic data), [**`ggfortify`**](https://cran.r-project.org/package=ggfortify) (simplified and automated plotting), et [**`traitdataform`**](https://cran.r-project.org/package=traitdataform) (metadata writing help for functional traits)
