# Skills

## Languages

French [native speaker]; English [C2, fluent speaker and scientific English]; Spanish [B1-B2, daily life]; German [A2-B1]; Chinese [A2-B1]; Japanese [A2]


## Programming languages

* \faRProject&nbsp;**R** &nbsp;\textbullet&nbsp; Best software development practices (unit tests with `testthat`, `pkgdown` web site, continuous integration/continuous deployment, CRAN submission) &nbsp;\textbullet&nbsp; data visualization (advanced `ggplot2` and extensions) &nbsp;\textbullet&nbsp; spatial data wrangling [`terra` rasters,`sf` vectors, PostGIS database, and interactions]
* \faPython&nbsp;**Python** &nbsp;\textbullet&nbsp; Object Oriented Programming &nbsp;\textbullet&nbsp; data wrangling with `pandas`
* \faDatabase&nbsp;**SQL** database interactions &nbsp;\textbullet&nbsp; high performance queries &nbsp;\textbullet&nbsp; interaction with `R` &nbsp;\textbullet&nbsp; spatial database PostgreSQL/PostGIS
* \faServer&nbsp;**High Performance Cluster** job submission on SLURM/SGE &nbsp;\textbullet&nbsp; array jobs and complex queries
* \faGit&nbsp;version control &nbsp;\textbullet&nbsp; git flow method &nbsp;\textbullet&nbsp; collaborative development with \faGithub&nbsp;GitHub
* Basic knowledge of **Julia**


## Statistics and Modelling

* Null models and permutation models for biodiversity
* Generalized Linear Mixed Models
* *Machine Learning*/*Artificial Intelligence*: *Random Forest*, *Support Vector Machine*
* Stage-structured population models, Lotka-Volterra models through Mathematica
